### ISSUE TITLE
No Name, No Format of files in the chart "My files"

### ISSUE THREAD

**Issue by TatianaSH** [amida-tech/dre-frontend#10]
The Files don't have Name, Format. No way to check content of the files. 
<img width="795" alt="screen shot 2015-10-19 at 3 51 22 pm" src="https://cloud.githubusercontent.com/assets/10200773/10589485/96bb1062-7679-11e5-9c8b-92dedbea8a5b.png">

**Comment by UglyEugen** [comment]
@kachok , @chaldon 
this issue is due to https://github.com/amida-tech/DRE-services/issues/1
