### ISSUE TITLE
Button "Delete Note" have rendering problem

### ISSUE THREAD

**Issue by TatianaSH** [amida-tech/dre-frontend#12]
Try to edit note, click button "Edit" > button "Delete note" becomes visible, but initially it partially rendered.
<img width="701" alt="screen shot 2015-10-26 at 10 27 11 am" src="https://cloud.githubusercontent.com/assets/10200773/10731650/c7f640cc-7bcc-11e5-8ada-9746a33e3611.png">

**Comment by UglyEugen** [comment]
@TatianaSH, what object you are testing on, what browser and its dimensions?

**Comment by TatianaSH** [comment]
Tested for medications but problem exists for any note type. Browser Safari, any size.
