### ISSUE TITLE
Button "...ENTRY" and round icon does not work for review notes

### ISSUE THREAD

**Issue by TatianaSH** [amida-tech/dre-frontend#13]
These buttons work only for medications. No chance to view notes for other items. 
<img width="808" alt="screen shot 2015-10-26 at 10 47 31 am" src="https://cloud.githubusercontent.com/assets/10200773/10732265/9c5fbefe-7bcf-11e5-8fa0-a4b063eb5129.png">

**Comment by igiware** [comment]
Some notes doesnt have related FHIR-resources, because of reloaded FHIR database. For such records added message "Related resource entry not found"
If resource is unsupported yet (like "insurance") "Resource entry unsupported" will be shown.
