### ISSUE TITLE
Empty "Gender" dropdown in "My Profile" -> "Edit"

### ISSUE THREAD

**Issue by chaldon** [amida-tech/dre-frontend#17]
Problem occur on fresh installation with empty databases.

**Comment by kachok** [comment]
All drop downs are looked up at ValueSet in FHIR, see dre-frontend/app/dre-frontend.mocks/scripts/services/dre-frontend-fhir-mocks.js
/cc @chaldon @mikehiner

We need to load those ValueSets to FHIR on bootstrap of DRE

**Comment by chaldon** [comment]
I had added ansible script to populate values to FHIR server but this step make deployment awkward and adds one more point to failure. No real necessity to have this valuesets in FHIR server. (IMHO)
