### ISSUE TITLE
Procedures have an entry with "Undefined" title.

### ISSUE THREAD

**Issue by chaldon** [amida-tech/dre-frontend#24]
This entry is imported from CMS (txt format) file and procedure have no SNOMED coding attached, so it needs some fallback text in the title.

**Comment by igiware** [comment]
http://www.hl7.org/fhir/procedure-definitions.html#Procedure.code is missed in data, but it described as required (control 1..1) in FHIR.
Loaded Resources contain only focalDevice field, so getting data from first action, if no procedure.code
