### ISSUE TITLE
Social history page is empty

### ISSUE THREAD

**Issue by chaldon** [amida-tech/dre-frontend#25]
My guess we have to show something for demo or hide it.

**Comment by kachok** [comment]
@chaldon need to add attribute to FHIR resource to mark it as Social History

category: 'social-history'

Example:

http://dre.ntrlab.ru:8080/fhir/baseDstu2/Observation/108268

 "category":{
                    "coding":[
                        {
                            "code":"social-history",
                            "display":"Social history"
                        }
                    ]
                },

**Comment by chaldon** [comment]
Fixed in parser.
