### ISSUE TITLE
Sources are empty

### ISSUE THREAD

**Issue by kachok** [amida-tech/dre-frontend#35]

**Comment by kachok** [comment]
@UglyEugen we are revisiting mechanism for sources, stand by

**Comment by kachok** [comment]
Preferred way is to have IDs to be full link/reference to BinaryResources

"extension":{
   "url":"http://amida-tech.com/fhir/source",
   "sources":[
          "id of original file",
          "id of update",
          "patient entered",
          "last update"
   ]
}

**Comment by igiware** [comment]
solved with d0ded90fa2ba7545b7424e83049da1e3b1aba9d7
