### ISSUE TITLE
Address and Phone doesn't save

### ISSUE THREAD

**Issue by chaldon** [amida-tech/dre-frontend#37]
Create a new user, edit address/phone and save - no NEW data added to Patient record

**Comment by UglyEugen** [comment]
sent request
PUT http://dre.ntrlab.ru:8080/fhir/baseDstu2/Patient/UglyEugen 
with no updated params
{"resourceType":"Patient","id":"UglyEugen","meta":{"versionId":"4","lastUpdated":"2015-11-19T15:57:58.205+03:00"},"identifier":[{"use":"usual","value":"UglyEugen"}],"name":[{"use":"usual","family":["Sluchanko"],"given":["Eugen"]}],"telecom":[{"system":"email","value":"dre.15.uglyeugen@spamgourmet.com"}],"gender":"Male","birthDate":"1977-01-30T21:00:00.000Z"}
