### ISSUE TITLE
Codeine allergy - merge keeps duplicate in FHIR

### ISSUE THREAD

**Issue by kachok** [amida-tech/dre-frontend#51]
Load 01,02,03 files for new user.

Merge Codeine allergies (by clicking "Save Updates"), in Allergies page one Codeine allergy has merged (has three sources), but original Codeine record (that was merged) is not deleted

**Comment by mhiner** [comment]
Can you give the output of the request and what boxes (if any) in the merge were selected?  Also was there any output in the browser console or dre-services?  I was able to merge 6 of the 7 matches and ignored 1 match without failure.

**Comment by kachok** [comment]
Don't see any errors in console. I merged/updated only Severity field

**Comment by mhiner** [comment]
if you refresh the browser window does the match go away?  Trying to confirm it is not a caching issue.
