### ISSUE TITLE
Source tab, all timestamps are 12:00 (not exact time file was uploaded)

### ISSUE THREAD

**Issue by kachok** [amida-tech/dre-frontend#52]

**Comment by igiware** [comment]
the reason is in valueDate without time
{
    "resourceType":"MedicationOrder",
    "id":"111997",
    "extension":[
        {
            "url":"http://amida-tech.com/fhir/extensions/source",
            "extension":[
                {
                    "url":"http://amida-tech.com/fhir/extensions/source/reference",
                    "valueString":"DocumentReference/178457/_history/1"
                },
                {
                    "url":"http://amida-tech.com/fhir/extensions/source/date",
                    "valueDate":"2015-12-01"
                },
                {
                    "url":"http://amida-tech.com/fhir/extensions/source/description",
                    "valueString":"Original source"
                }
            ]
        }
    ],
...
Patient entered resources store full time stamp
{
                "resourceType":"MedicationOrder",
                "id":"226026",
                "extension":[
                    {
                        "url":"http://amida-tech.com/fhir/extensions/source",
                        "extension":[
                            {
                                "url":"http://amida-tech.com/fhir/extensions/source/date",
                                "valueDate":"2015-12-07T11:37:06.816Z"
                            },
                            {
                                "url":"http://amida-tech.com/fhir/extensions/source/description",
                                "valueString":"Patient entered"
                            }
                        ]
                    }
                ],
...

**Comment by kachok** [comment]
But when we display "My Files" - http://localhost:9000/#/home/files we have proper time there, can we use the same values?

**Comment by igiware** [comment]
i'll try to update indexed value from DocumentReference resource

**Comment by igiware** [comment]
@kachok,
changed indexed data priority, so timestamp is same in files & sources
