### ISSUE TITLE
Button "Print my record" does not work

### ISSUE THREAD

**Issue by TatianaSH** [amida-tech/dre-frontend#7]
No  functionality assigned to button "Print my record" and "Blue Button Download my Data"
<img width="772" alt="screen shot 2015-10-19 at 11 32 15 am" src="https://cloud.githubusercontent.com/assets/10200773/10588251/2af65446-7673-11e5-8335-36bce45e687a.png">

**Comment by igiware** [comment]
FYI, Print My Record overloads network.
For each block (Allergy, Medications, Procedures, etc) requesting 30 recent records, for each record requesting for sources. If selected  additional data, then for each found record requesting notes. 
For some rescords like Medications, requesting several additional data to resolve internal FHIR-references.

Currently, on test data, Print My Record makes over 500 requests and loads about 50MB.
