### ISSUE TITLE
records have Title "UNDEFINED"  

### ISSUE THREAD

**Issue by TatianaSH** [amida-tech/dre-frontend#9]
Each record have Title "UNDEFINED"  in the charts: IMMUNIZATIONS, ALLERGIES, PROCEDURES
<img width="534" alt="screen shot 2015-10-19 at 3 15 53 pm" src="https://cloud.githubusercontent.com/assets/10200773/10588688/683268d4-7675-11e5-86fe-d9e87429a804.png">
<img width="542" alt="screen shot 2015-10-19 at 3 16 10 pm" src="https://cloud.githubusercontent.com/assets/10200773/10588694/6e0c85a0-7675-11e5-8914-77e4f032daec.png">
<img width="514" alt="screen shot 2015-10-19 at 3 16 25 pm" src="https://cloud.githubusercontent.com/assets/10200773/10588698/71a5c56e-7675-11e5-84f7-7affd372a56b.png">

**Comment by igiware** [comment]
one Procedure resource was updated manually in FHIR: so it has procedure codable data and title as result. Other records - doesnt
